"""Export-only ``requirements`` backend.

Walks the same install pipeline as conda / uv but writes the collected
deps to a ``requirements.txt``-style file instead of installing them.
Conda-channel entries and shell install scripts are recorded in a
"manual steps" section since they cannot be expressed as PyPI lines.

The backend does not create or modify any environment. ``--env`` /
``--env-name`` are rejected at the CLI level.
"""
from pathlib import Path

from .base import EnvBackend


_DEFAULT_OUTPUT = "requirements.txt"


class RequirementsBackend(EnvBackend):
    """:class:`EnvBackend` that emits a ``requirements.txt`` instead of
    installing anything. See module docstring for design.

    Accumulation state is held on the class (singleton): the orchestrator
    instantiates the backend repeatedly through ``get_backend()``, so the
    state must outlive any single instance. There is only ever one active
    export at a time per ``benchopt install`` invocation.
    """

    name = "requirements"

    output_path: str = _DEFAULT_OUTPUT
    manual_output_path: str = ""

    _pip_packages: list = []
    _manual_lines: list = []
    _header_lines: list = []

    # ------------------------------------------------------------------
    # CLI plumbing
    # ------------------------------------------------------------------
    @classmethod
    def configure_output(cls, output_path=None, manual_output_path=None,
                         benchmark_name=None, python_version=None):
        """Reset accumulators and pin the destination file(s)."""
        cls.output_path = output_path or _DEFAULT_OUTPUT
        cls.manual_output_path = manual_output_path or ""
        cls._pip_packages = []
        cls._manual_lines = []
        cls._header_lines = [
            "# Generated by benchopt install --backend requirements",
        ]
        if benchmark_name:
            cls._header_lines.append(f"# Benchmark: {benchmark_name}")
        if python_version:
            cls._header_lines.append(f"# Python: {python_version}")

    # ------------------------------------------------------------------
    # EnvBackend protocol — env-management methods are no-ops by design
    # ------------------------------------------------------------------
    def list_envs(self):
        return (None, [])

    def get_env_info(self, env_name):
        return dict(version=None, is_editable=False,
                    python_version=None, pytest_version=None)

    def is_active_env_compatible(self):
        # No env required to write a file.
        return True

    def create_env(self, env_name, *, benchmark=None, recreate=False,
                   pytest=False, empty=False, quiet=False):
        raise RuntimeError(
            "The 'requirements' backend does not create environments. "
            "Run `benchopt install --backend requirements` without "
            "--env / --env-name."
        )

    def delete_env(self, env_name):
        raise RuntimeError(
            "The 'requirements' backend does not manage environments."
        )

    def run_in_env(self, script, *, env_name=None, raise_on_error=None,
                   capture_stdout=True, return_output=False):
        raise NotImplementedError(
            "The 'requirements' backend does not run commands in envs."
        )

    # ------------------------------------------------------------------
    # Package install — actually classify and record
    # ------------------------------------------------------------------
    def can_install(self, requirement):
        # Capture every requirement (pip or chan) so the user gets the
        # full picture in the export. Partitioning into PyPI lines vs.
        # manual steps happens in ``install_packages``.
        return True

    def install_packages(self, *packages, env_name=None, quiet=False):
        for pkg in packages:
            self._record_one(pkg)
        self._flush()

    def install_shell_script(self, script, *, env_name=None, quiet=False):
        self._manual_lines.append(
            f"# Shell install script: {script}\n"
            f"#   bash \"{script}\" <env-prefix>"
        )
        self._flush()

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _record_one(self, requirement):
        normalized = requirement
        if ":" in normalized and "::" not in normalized:
            normalized = normalized.replace(":", "::", 1)
        if normalized.startswith("pip::"):
            self._pip_packages.append(normalized[len("pip::"):])
        elif "::" in normalized:
            channel, name = normalized.split("::", 1)
            self._manual_lines.append(
                f"# Conda dependency (channel: {channel}): {name}\n"
                f"#   conda install -c {channel} {name}"
            )
        else:
            # Bare name → assume PyPI-installable.
            self._pip_packages.append(normalized)

    def _flush(self):
        cls = type(self)
        out = Path(cls.output_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        # Dedupe pip packages while preserving order.
        seen = set()
        deduped_pkgs = []
        for p in cls._pip_packages:
            if p not in seen:
                deduped_pkgs.append(p)
                seen.add(p)

        manual_out = (
            Path(cls.manual_output_path)
            if cls.manual_output_path else out
        )

        with open(out, "w") as f:
            if cls._header_lines:
                f.write("\n".join(cls._header_lines) + "\n")
            for p in deduped_pkgs:
                f.write(p + "\n")
            if manual_out == out and cls._manual_lines:
                f.write("\n# Manual steps — items not installable via pip:\n")
                for line in cls._manual_lines:
                    f.write(line + "\n")

        if manual_out != out and cls._manual_lines:
            manual_out.parent.mkdir(parents=True, exist_ok=True)
            with open(manual_out, "w") as f:
                f.write(
                    "# Items not installable via pip — install manually:\n\n"
                )
                for line in cls._manual_lines:
                    f.write(line + "\n")


__all__ = ["RequirementsBackend"]
