.. _Thomas Moreau: https://tommoral.github.io

.. _Alexandre Gramfort: http://alexandre.gramfort.net

.. _Joseph Salmon: http://josephsalmon.eu

.. _Mathurin Massias: https://mathurinm.github.io

.. _Tanguy Lefort: https://github.com/tanglef

.. _Tom Dupré La Tour: https://tomdlt.github.io

.. _Nidham Gazagnadou: https://ngazagna.github.io

.. _Ghislain Durif: https://gdurif.perso.math.cnrs.fr/

.. _Benoît Malézieux: https://github.com/bmalezieux

.. _Amélie Vernay: https://github.com/AmelieVernay
