.. _Thomas Moreau: https://tommoral.github.io

.. _Alexandre Gramfort: http://alexandre.gramfort.net

.. _Joseph Salmon: http://josephsalmon.eu

.. _Mathurin Massias: https://mathurinm.github.io

.. _Tanguy Lefort: https://github.com/tanglef

.. _Tom Dupré La Tour: https://tomdlt.github.io

.. _Nidham Gazagnadou: https://ngazagna.github.io

.. _Ghislain Durif: https://gdurif.perso.math.cnrs.fr/

.. _Benoît Malézieux: https://github.com/bmalezieux

.. _Amélie Vernay: https://github.com/AmelieVernay

.. _Melvine Nargeot: https://github.com/Melvin-klein

.. _Badr Moufad: https://github.com/Badr-MOUFAD

.. _Pierre Ablin: https://github.com/pierreablin

.. _Christopher Marouani: https://github.com/chris-mrn

.. _Célestin Eve: https://github.com/ceelestin

.. _Pierre-Antoine Comby: https://github.com/paquiteau

.. _Virginie Loison: https://www.linkedin.com/in/virginie-loison/

.. _Julie Alberge: https://www.linkedin.com/in/julie-alberge

.. _Jad Yehya: https://github.com/Jad-yehya

.. _Mathieu Dagréou: https://matdag.github.io
