name: Expose result artifact
on: [status]
# Cancel in-progress workflows when pushing
# a new commit on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  circleci_result_artifact_redirector_job:
    runs-on: ubuntu-latest
    name: Link to CircleCI result artifact
    steps:
      - name: Redirect to Circle CI artifact
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/result.html
          circleci-jobs: build_docs
          job-title: benchmark result artifact
          api-token: ${{ secrets.CIRCLE_CI_STATUS_TOKEN }}
  circleci_docs_artifact_redirector_job:
    runs-on: ubuntu-latest
    name: Link to CircleCI documentation artifact
    steps:
      - name: Redirect to Circle CI artifact
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: build_docs
          api-token: ${{ secrets.CIRCLE_CI_STATUS_TOKEN }}
