name: Expose artifact links
on: [status]
jobs:
  circleci_result_artifact_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI result artifact redirector
    steps:
      - name: Redirect to Circle CI artifact
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/result.html
          circleci-jobs: build_docs

  circleci_docs_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: build_docs
