name: Create HTML artifact

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  circleci_result_artifact_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI result artifact redirector
    steps:
      - name: Redirect to Circle CI artifact
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/result.html
          circleci-jobs: build_docs
