name: no_conda_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tags:
      - "**"
  schedule:
    # Run every day at 8:42am UTC.
    - cron: "42 8 * * *"

jobs:
  test_benchopt:
    name: Test without conda
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version_python: 3.9
          - os: macos-latest
            version_python: 3.9
    env:
      JUNIT_XML: "test-data.xml"
      VERSION_PYTHON: ${{ matrix.version_python }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.VERSION_PYTHON }}

      - name: Install benchopt and its dependencies
        run: pip install -e .

      - name: Run benchopt without conda
        run: benchopt run benchopt/tests/test_benchmarks/dummy_benchmark
